services:
  - type: web
    name: kevin-vs-ivonne-mundial-2026
    runtime: node
    plan: free
    buildCommand: ""
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
